# Generated by Django 4.1.3 on 2022-11-20 10:50

from django.db import migrations


def migration_up(apps, schema_editor):
    SecretSanta = apps.get_model("core", "SecretSanta")

    SecretSanta.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migration_up, migrations.RunPython.noop),
    ]
