# Generated by Django 4.1.3 on 2022-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='hashed_member_info',
            new_name='hashed_email',
        ),
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
    ]
