# Generated by Django 4.1.3 on 2022-11-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221120_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretsanta',
            name='celebration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='secret_santas', to='core.celebration'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='secretsanta',
            unique_together={('santa', 'recipient', 'celebration')},
        ),
    ]
